import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { renderToBuffer } from "@react-pdf/renderer";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";

// ─────────────────────────────────────────────
// Styles
// ─────────────────────────────────────────────

const styles = StyleSheet.create({
  page: {
    padding: 50,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: "#1a1a1a",
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: "#2563eb",
    paddingBottom: 12,
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: "Helvetica-Bold",
    color: "#2563eb",
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    marginBottom: 4,
  },
  headerDate: {
    fontSize: 9,
    color: "#666",
  },
  sectionTitle: {
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    color: "#1e3a5f",
    marginTop: 16,
    marginBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    paddingBottom: 4,
  },
  text: {
    fontSize: 10,
    lineHeight: 1.5,
    marginBottom: 6,
  },
  summaryLine: {
    fontSize: 10,
    lineHeight: 1.6,
    marginBottom: 2,
  },
  // Valuation table styles
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    paddingVertical: 6,
  },
  tableHeader: {
    flexDirection: "row",
    borderBottomWidth: 2,
    borderBottomColor: "#2563eb",
    paddingVertical: 6,
    marginBottom: 2,
  },
  tableCell: {
    flex: 1,
    fontSize: 10,
  },
  tableCellBold: {
    flex: 1,
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
  },
  tableCellRight: {
    flex: 1,
    fontSize: 10,
    textAlign: "right",
  },
  tableCellRightBold: {
    flex: 1,
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    textAlign: "right",
  },
  // DD checklist styles
  checkItem: {
    flexDirection: "row",
    marginBottom: 4,
  },
  checkBox: {
    width: 14,
    fontSize: 10,
    marginRight: 6,
  },
  checkText: {
    flex: 1,
    fontSize: 10,
    lineHeight: 1.4,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 50,
    right: 50,
    textAlign: "center",
    fontSize: 8,
    color: "#999",
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    paddingTop: 8,
  },
});

// ─────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────

interface ValuationTier {
  multiple: number;
  impliedPrice: number;
}

interface ValuationSnapshot {
  adjustedEbitda: number | null;
  earningsType: string | null;
  conservative: ValuationTier | null;
  target: ValuationTier | null;
  stretch: ValuationTier | null;
  comparableCount: number;
}

interface DDItem {
  itemText: string;
  isCompleted: boolean;
}

// ─────────────────────────────────────────────
// PDF Document Component
// ─────────────────────────────────────────────

function PriorityADocument({
  companyName,
  date,
  executiveSummary,
  acquisitionThesis,
  valuation,
  ddItems,
}: {
  companyName: string;
  date: string;
  executiveSummary: string;
  acquisitionThesis: string;
  valuation: ValuationSnapshot;
  ddItems: DDItem[];
}) {
  const fmtCurrency = (n: number) =>
    `$${n.toLocaleString("en-US", { maximumFractionDigits: 0 })}`;
  const fmtMultiple = (n: number) => `${n.toFixed(2)}x`;

  return (
    <Document>
      {/* Page 1: Summary + Thesis */}
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.headerTitle}>PRIORITY A — DEAL PACKAGE</Text>
          <Text style={styles.headerSubtitle}>{companyName}</Text>
          <Text style={styles.headerDate}>Generated {date}</Text>
        </View>

        <Text style={styles.sectionTitle}>Executive Summary</Text>
        {executiveSummary.split("\n").map((line, i) => (
          <Text key={i} style={styles.summaryLine}>
            {line.replace(/\*\*/g, "")}
          </Text>
        ))}

        <Text style={styles.sectionTitle}>Acquisition Thesis</Text>
        {acquisitionThesis.split("\n\n").map((para, i) => (
          <Text key={i} style={styles.text}>
            {para.trim()}
          </Text>
        ))}

        <Text style={styles.footer}>
          Generated by DealFlow — Confidential
        </Text>
      </Page>

      {/* Page 2: Valuation + DD Checklist */}
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.sectionTitle}>Valuation Snapshot</Text>

        {valuation.adjustedEbitda ? (
          <Text style={styles.text}>
            Adjusted EBITDA: {fmtCurrency(valuation.adjustedEbitda)}
            {valuation.earningsType ? ` (${valuation.earningsType})` : ""}
            {" | "}
            {valuation.comparableCount} comparable transaction
            {valuation.comparableCount !== 1 ? "s" : ""}
          </Text>
        ) : (
          <Text style={styles.text}>
            No earnings data available for valuation.
          </Text>
        )}

        {valuation.comparableCount > 0 ? (
          <View>
            <View style={styles.tableHeader}>
              <Text style={styles.tableCellBold}>Scenario</Text>
              <Text style={styles.tableCellRightBold}>Multiple</Text>
              <Text style={styles.tableCellRightBold}>Implied Price</Text>
            </View>

            <View style={styles.tableRow}>
              <Text style={styles.tableCell}>Conservative (P25)</Text>
              <Text style={styles.tableCellRight}>
                {valuation.conservative
                  ? fmtMultiple(valuation.conservative.multiple)
                  : "N/A"}
              </Text>
              <Text style={styles.tableCellRight}>
                {valuation.conservative
                  ? fmtCurrency(valuation.conservative.impliedPrice)
                  : "N/A"}
              </Text>
            </View>

            <View style={styles.tableRow}>
              <Text style={styles.tableCell}>Target (Median)</Text>
              <Text style={styles.tableCellRight}>
                {valuation.target
                  ? fmtMultiple(valuation.target.multiple)
                  : "N/A"}
              </Text>
              <Text style={styles.tableCellRight}>
                {valuation.target
                  ? fmtCurrency(valuation.target.impliedPrice)
                  : "N/A"}
              </Text>
            </View>

            <View style={styles.tableRow}>
              <Text style={styles.tableCell}>Stretch (P75)</Text>
              <Text style={styles.tableCellRight}>
                {valuation.stretch
                  ? fmtMultiple(valuation.stretch.multiple)
                  : "N/A"}
              </Text>
              <Text style={styles.tableCellRight}>
                {valuation.stretch
                  ? fmtCurrency(valuation.stretch.impliedPrice)
                  : "N/A"}
              </Text>
            </View>
          </View>
        ) : (
          <Text style={styles.text}>
            No BVR comparable transactions available for this target type.
          </Text>
        )}

        {ddItems.length > 0 && (
          <View>
            <Text style={styles.sectionTitle}>
              Due Diligence Checklist (Pre-NDA)
            </Text>
            {ddItems.map((item, i) => (
              <View key={i} style={styles.checkItem}>
                <Text style={styles.checkBox}>
                  {item.isCompleted ? "\u2611" : "\u2610"}
                </Text>
                <Text style={styles.checkText}>{item.itemText}</Text>
              </View>
            ))}
          </View>
        )}

        <Text style={styles.footer}>
          Generated by DealFlow — Confidential
        </Text>
      </Page>
    </Document>
  );
}

// ─────────────────────────────────────────────
// GET — Export Priority A package as PDF
// ─────────────────────────────────────────────

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const { id } = await params;

    // 1. Fetch PriorityAPackage
    const pkg = await prisma.priorityAPackage.findUnique({
      where: { listingId: id },
    });

    if (!pkg) {
      return NextResponse.json(
        { error: "No package generated yet. Call POST first." },
        { status: 404 },
      );
    }

    // 2. Fetch listing for context
    const listing = await prisma.listing.findUnique({
      where: { id },
      select: {
        businessName: true,
        title: true,
      },
    });

    // 3. Fetch DD items for checklist section (Pre-NDA only)
    const ddItems = await prisma.dueDiligenceItem.findMany({
      where: { listingId: id, stage: "PRE_NDA" },
      orderBy: { order: "asc" },
      select: { itemText: true, isCompleted: true },
    });

    // 4. Parse valuation snapshot from JSON
    const valuation = (pkg.valuationSnapshot as unknown as ValuationSnapshot) ?? {
      adjustedEbitda: null,
      earningsType: null,
      conservative: null,
      target: null,
      stretch: null,
      comparableCount: 0,
    };

    const companyName =
      listing?.businessName || listing?.title || "Unknown Company";
    const date = new Date().toISOString().split("T")[0];

    // 5. Render PDF
    const buffer = await renderToBuffer(
      <PriorityADocument
        companyName={companyName}
        date={date}
        executiveSummary={pkg.executiveSummary}
        acquisitionThesis={pkg.acquisitionThesis}
        valuation={valuation}
        ddItems={ddItems}
      />,
    );

    const safeName = (companyName).replace(
      /[^a-zA-Z0-9]/g,
      "-",
    );

    return new Response(buffer as unknown as BodyInit, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="Priority-A-${safeName}-${date}.pdf"`,
      },
    });
  } catch (err) {
    console.error("[Priority A PDF]", err);
    return NextResponse.json(
      { error: "Failed to generate PDF" },
      { status: 500 },
    );
  }
}
